site_name: Xournal++
repo_url: https://github.com/xournalpp/xournalpp/
repo_name: xournalpp/xournalpp
remote_branch: master
edit_uri: https://github.com/xournalpp/xournalpp.github.io/edit/site/docs
nav:
  - Home: index.md
  - Install: installation.md
  - Guide:
      - Overview: guide/overview.md
      - Configuration: guide/config.md
      - Tools and Editing:
         - Pen and Highlighter tools: guide/tools/pen.md
         - Eraser tool: guide/tools/eraser.md
         - Selection and Snapping tools: guide/tools/selecsnap.md
         - LaTeX tool: guide/tools/latex.md
      - Plugins: 
         - Bulding plugins: guide/plugins/plugins.md
         - Notable plugins: guide/plugins/notable.md
      - Tips: guide/tips.md
  - Community: community.md
  - "Report a bug": https://github.com/xournalpp/xournalpp/issues 

#Theme config
theme: 
  name: material
  favicon: img/favicon.ico
  logo: img/favicon.ico
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: default
    primary: indigo
    accent: deep orange
  features:
    - navigation.tabs
    - toc.integrate

#Enable macros
plugins:
  - search
  - macros    

extra:
  version:
    latest_stable: "1.0.20"
    latest_unstable: "1.1.0+dev"

#code highlighting
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true
